export const TYPES = {

  ANSWER_SELECT: {
    MOUNT: '[ANSWER_SELECT] MOUNT',
    REMOVE: '[ANSWER_SELECT] REMOVE'
  },
  QUESTIONS: {
    ADD: '[QUESTIONS] ADD'
  },
  SCORE: {
    TOTAL_POINTS: '[SCORE] TOTAL_POINTS',
    WRONG_ANSWER: '[SCORE] WRONG_ANSWER',
    CORRECT_ANSWER: '[SCORE] CORRECT_ANSWER',
    TOTAL_QUESTION: '[SCORE] TOTAL_QUESTION',
  },
  ANSWERS: {
    ADD: '[ANSWERS] ADD',
  },
  USER: {
    LOGGIN: '[USER] LOGGIN',
    LOGOUT: '[USER] LOGOUT',
    CHANGE_NAME: '[USER] CHANGE NAME',
  },
  GAME_STATUS: {
    SET_CURRENT_QUESTION_INDEX: '[GAME_STATUS] SET_CURRENT_QUESTION_INDEX',
  },
}
